# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       ncdu

# >> macros
# << macros

Summary:    NCurses Disk Usage
Version:    1.16
Release:    0
Group:      Applications
License:    MIT
URL:        https://dev.yorhel.nl/ncdu
Source0:    %{name}-%{version}.tar.gz
Source100:  ncdu.yaml
BuildRequires:  pkgconfig(ncursesw)
BuildRequires:  autoconf
BuildRequires:  automake

%description

ncdu (NCurses Disk Usage) is a curses-based version of the well-known 'du',
and provides a fast way to see what directories are using your disk space.

%if "%{?vendor}" == "chum"
Type: console-application
PackagerName: nephros
Categories:
 - Utility
 - ConsoleOnly
Custom:
  Repo: https://g.blicky.net/ncdu.git
  PackagingRepo: https://github.com/sailfishos-chum/ncdu
Screenshots:
  - https://dev.yorhel.nl/img/ncduscan-2.png
  - https://dev.yorhel.nl/img/ncdudone-2.png
  - https://dev.yorhel.nl/img/ncduinfo-2.png
Url:
  Homepage: https://dev.yorhel.nl/ncdu
  Help: https://dev.yorhel.nl/ncdu/man
  Bugtracker: https://code.blicky.net/yorhel/ncdu/issues
  Donation: https://dev.yorhel.nl/contributing.html
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --with-ncursesw

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
rm -rf %{buildroot}%{_mandir}
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/*
# >> files
# << files
